version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/dashboard
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /apps/volunteer
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /services/api
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
